DROP TABLE IF EXISTS unidade CASCADE;
DROP SEQUENCE IF EXISTS seq_unidade;

CREATE SEQUENCE seq_unidade INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 START 1 CACHE 1;
CREATE TABLE unidade (
	id INTEGER,
	numeroLote INTEGER,
	nome VARCHAR(128),
	createdAt TIMESTAMP,
	updatedAt TIMESTAMP
);

ALTER TABLE unidade ADD CONSTRAINT unidade_pk PRIMARY KEY (id);

ALTER TABLE unidade ALTER COLUMN nome SET NOT NULL;

ALTER TABLE unidade ALTER COLUMN createdAt SET NOT NULL;

ALTER TABLE unidade ALTER COLUMN updatedAt SET NOT NULL;